### ISSUE TITLE
Cryptopp-static.lib LINK error

### ISSUE THREAD

**Issue by Xintari** [Open-Games-Community/Hellgrave-RPG-v6.0#1]
Hello, I am using Visual Studio Community 2022

And all compiles well but it fails at the linking stage with the following error:

hellgrave\out\build\x64-Debug\LINK : fatal error LNK1181: cannot open input file 'cryptopp-static.lib'

LNK1181	cannot open input file 'cryptopp-static.lib'	hellgrave\out\build\x64-Debug\hellgrave	hellgrave\out\build\x64-Debug\LINK

I am on Windows 10 as well.

**Comment by Alexv45** [comment]
Hello @Xintari 

You can download already [pre-compiled here](https://opengamescommunity.com/index.php?resources/hellgrave-rpg-server-v6-0-windows.843/). But also downloading it from here, you will see a folder called ' Compilation_Crypto'.

Inside you will find a info.txt, explaining, how to solve this error on windows:

While compiling, it's possible you got an error from CryptoLib or CryptoPP or something like this.

To fix this:

Enter on data/out/built/x64-Release/vcpkg-installed/x64-windows/lib

Replace Cryptopp-static.lib with the new one on the folder.

Enter on data/out/build/x64-Release/vcpkg-installed/x64-windows/debug/lib

Replace Crytpopp-static.lib with the new one on the folder.

Close The Folder.

Open Visual Studio and compile again.

This will work on Windows only.

**Comment by Xintari** [comment]
Oh perfect, I followed the instructions and it worked. Thank you for your quick response.
